### ISSUE TITLE
Segmentation fault occurs when subscribed to a topic

### ISSUE THREAD

**Issue by avinashs24** [Auctoris/mosquitopp_client#1]
Hi,
I'm trying to use your library. After connecting with the broker, I want to subscribe to a topic. But whenever I try that, segmentation fault occurs. When I comment out the subscribe line, program is fine. Publishing works fine too. Please help.

**Comment by Auctoris** [comment]
I can't reproduce this error. I suggest you try to raise an issue at the master repo for the underlying Mosquitto library here: https://github.com/eclipse/mosquitto
